### PR TITLE
Fixes #21: Implemented Wheel of Fortune Game 

### LINKED ISSUE #21: Create a Wheel of Fortune Game in Js

### PR DESCRIPTION
**Pull request by anushkp1107**
This Wheel of Fortune game simulates the TV show experience with a simplified interface. Players spin the wheel to determine their potential score, with a hint about the puzzle word's length and spaces provided on the first spin. They can guess letters or attempt to solve the puzzle. Correct letter guesses increase their score, while incorrect ones deduct points. Solving the puzzle rewards bonus points. Passing a turn resets the score. The game encourages players to accumulate points while trying to solve the puzzle, mimicking the classic TV game show's excitement and challenge.

### CODE REVIEW

**Comment by anushkp1107** [comment]
@Aanchi-glitch2744 kindly review and merge my PR under hacktoberfest-accepted label

**Comment by Aanchi-glitch2744** [comment]
Can you explain me how your game is working?
I can't understand it from this: 
Screenshot (21)

**Comment by anushkp1107** [comment]
Yaa sure...

When the spin button is clicked for the first time, it shows hints related to the word or sentence to be guessed. Here in my game the word to be guessed is WHEEL OF FORTUNE. Now if you want to guess letters that could be present in the phrase, enter the guessed letter in the space provided. Suppose you guessed H to be present in the phrase, then the result box shows correct guess increasing the player's score by 100. If the guess is incorrect then the player's score is deducted by 50. Likewise with the help of guessing functionality and hints provided like number of letters and spaces in the phrase, the player can guess the whole phrase. If you entered correct phrase in the input box and clicked solve then the score is increased by 500 else if it is wrong then the score is deducted by 100.

You can restart the game by clicking again on the spin button or you may pass to the next player. In both cases the player's score is reset to 0.

There are 4 main buttons:
1. Spin: To start or restart the game.
2. Guess Letter: To guess the letters present in the phrase.
3. Solve: To check whether the guessed phrase is correct or not.
4. Pass: To pass the turn to next player.

**Comment by Aanchi-glitch2744** [comment]
As per image shared by me, you can see arc (dark orange) in the circle moves very unaligned with the circle, replace it such that arc is matching with the circumference and the tip is at the center of the wheel. Also the S.. and 2 inside the Arc shall not be visible. It rotates with the arc and makes the game confusing.

**Comment by Aanchi-glitch2744** [comment]
I'm accepting your code due to proper functionality, but I still see a score for improvement for the arc inside the wheel

**Review by Aanchi-glitch2744 — APPROVED** [review]

**Pull request merged**
