### PR TITLE
Added the Rabbit Rush Game

### PR DESCRIPTION
**Pull request by aditya-agr**

### CODE REVIEW

**Review by Aanchi-glitch2744 — APPROVED** [review]
I'm thankful you contributed to our repo, this is the kind of content I was looking for. Great job aditya!

**Comment by aditya-agr** [comment]
Why this repo has been excluded from the hacktoberfest

**Comment by Aanchi-glitch2744** [comment]
Hello @aditya-agr,
This repo is not excluded, but I guess it happend bcuz I shifted your code from base folder to JavaScriptGameLogic folder after merge. Can do Do one thing, Add same game inside JavaScriptGameLogic folder as RabbitGame2 folder and I'll accept ypur PR again. 
Happy Hacking!

**Comment by aditya-agr** [comment]
Ok I will do.

**Pull request merged**
