### PR TITLE
Implemented typing speed test game

### PR DESCRIPTION
**Pull request by anushkp1107**

### CODE REVIEW

**Review by Aanchi-glitch2744 — CHANGES_REQUESTED** [review]
Hello @anushkp1107,
Kindly resolve the bug and I'll merge your code.
Bug: Doesn't show the text for typing.
Screenshot (23)

**Comment by anushkp1107** [comment]
@Aanchi-glitch2744 you have to type the given text. The given text is "Keep calm and code on". Type this and proceed as directed.

**Comment by Aanchi-glitch2744** [comment]
Ok that's fine, but there's one more issue, i.e. the Words per minute count is not increasing. @anushkp1107

**Comment by anushkp1107** [comment]
@Aanchi-glitch2744 I tried resolving the issue by increasing the number of quotes to write. Wpm count was not increasing due to less writing matter. More writing matter will resolve this issue. Please review these changes.

**Review by Aanchi-glitch2744 — APPROVED** [review]

**Pull request merged**
